# Numpy Exercises

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print (np.version.version)

1.14.0


#### 3. Create a null vector of size 10 (★☆☆)

In [15]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [10]:
print("%d bytes" % (a.size * a.itemsize))

80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
b = np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
c = np.arange(10, 50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [23]:
d = c[::-1]
d

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [25]:
e = np.arange(9).reshape((3,3))
e

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [26]:
e = np.nonzero([1,2,0,0,4,0])
e

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [32]:
f = np.random.random((3,3,3))
f

array([[[0.74586656, 0.58104819, 0.2566096 ],
        [0.45906047, 0.10091921, 0.8089268 ],
        [0.05923969, 0.63308865, 0.91781333]],

       [[0.5089946 , 0.32659073, 0.15819221],
        [0.79046589, 0.69696791, 0.71551353],
        [0.11653548, 0.77250885, 0.61996221]],

       [[0.55237345, 0.40056559, 0.69251622],
        [0.72869377, 0.1424725 , 0.92126356],
        [0.90203394, 0.09893285, 0.69351349]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [38]:
g = np.random.random((10,10))
print(g)
print (np.max(g))
print (np.min(g))

[[0.40035053 0.22805707 0.16424508 0.2857234  0.29415919 0.07065868
  0.24567084 0.5503616  0.08741321 0.2760296 ]
 [0.94406465 0.07361046 0.31909298 0.80192233 0.07085069 0.03757341
  0.33728737 0.57869721 0.61106379 0.66551775]
 [0.90566847 0.07944094 0.46777229 0.05093407 0.88479488 0.29674932
  0.40867512 0.24959938 0.9434277  0.35544345]
 [0.27333484 0.01929425 0.83732776 0.02437556 0.976137   0.71082593
  0.61167418 0.14398477 0.60052778 0.86904792]
 [0.48174781 0.58177323 0.47766666 0.42683263 0.27234365 0.15177152
  0.92718789 0.6291928  0.9051129  0.56403649]
 [0.87771898 0.23678274 0.98272599 0.07906498 0.56027872 0.36629163
  0.49225829 0.76493521 0.09177608 0.06211599]
 [0.83074878 0.76792039 0.55004266 0.01646975 0.53335594 0.70040646
  0.6323497  0.72990078 0.00731084 0.07177619]
 [0.14220256 0.76654656 0.12821385 0.26246906 0.06460894 0.77664039
  0.9963474  0.17249423 0.25765253 0.33348107]
 [0.0817018  0.29079699 0.10855155 0.28558581 0.77410064 0.79657209
  0.48393416

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [41]:
h = np.random.random(30)
print (h)
print(np.mean(h))

[0.02126953 0.44693587 0.48707378 0.34103033 0.01678028 0.66647233
 0.43428821 0.41632491 0.83605757 0.76428661 0.77236071 0.77245459
 0.68509634 0.94606481 0.21308403 0.24262381 0.26327748 0.6963171
 0.16141165 0.4501942  0.63279407 0.36532865 0.7349666  0.37136405
 0.92158745 0.26498024 0.61093935 0.02542159 0.4819902  0.50143627]
0.4848070866347579


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [47]:
i = np.ones((8, 8))
i[1:-1,1:-1] = 0
i

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [49]:
j = np.pad(i, pad_width=1, mode='constant', constant_values=0)
j

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [62]:
0 * np.nan

nan

In [63]:
np.nan == np.nan

False

In [64]:
np.inf > np.nan

False

In [65]:
np.nan - np.nan

nan

In [66]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [67]:
np.diag([1, 2, 3, 4], k= -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [77]:
k = np.ones((8, 8))
k[1::2, ::2] = 0
k[::2, 1::2] = 0
k

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [89]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [91]:
m = np.tile(np.array([[0,1],[1,0]]), (4,4))
m

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [94]:
n = np.random.random((5,5))
n_max, n_min = np.max(n), np.min(n)
o = (n - n_min)/(n_max - n_min)
print(n)
print(o)

[[0.597111   0.05411088 0.72747475 0.10438505 0.06573696]
 [0.34159034 0.96611883 0.66318037 0.49870782 0.03780592]
 [0.59207339 0.23651333 0.75525668 0.93207558 0.50756509]
 [0.23847553 0.96455614 0.29403649 0.30222389 0.02126583]
 [0.52810334 0.03749724 0.42490107 0.89872894 0.85694205]]
[[0.60945477 0.03476207 0.74742729 0.08797053 0.04706672]
 [0.33902047 1.         0.67938032 0.50530822 0.01750546]
 [0.60412313 0.22781057 0.77683073 0.96396978 0.51468245]
 [0.22988729 0.9983461  0.28869111 0.29735637 0.        ]
 [0.53641943 0.01717877 0.42719369 0.92867685 0.88445103]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [97]:
p = np.dtype([('r', np.ubyte, 1),('g', np.ubyte, 1),('b', np.ubyte, 1),('a', np.ubyte, 1)])
print(p)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [98]:
np.dot(np.random.random((5,3)), np.random.random((3,2)))

array([[0.90856125, 0.93433804],
       [1.27678642, 1.34118694],
       [1.11887534, 1.11883763],
       [0.87302384, 0.89507028],
       [0.95179316, 1.09277305]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [103]:
q = np.array([1, 10, 25, 2, 7, 8, 9, 4, 5, 0, 3])
q[(q>=3) & (q<=8)] *= -1
q

array([ 1, 10, 25,  2, -7, -8,  9, -4, -5,  0, -3])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [104]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [114]:
Z = np.ones(8)
print(Z**Z)
# print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)

[1. 1. 1. 1. 1. 1. 1. 1.]
[False False False False False False False False]
[0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j 0.+1.j]
[1. 1. 1. 1. 1. 1. 1. 1.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [116]:
np.array(0) / np.array(0)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [117]:
np.array(0) // np.array(0)

C:\Users\DELL\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [118]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])